baseURL = 'https://handling1.github.io/unarocaenelmar/'
languageCode = 'en-us'
title = 'Una Roca en el Mar'
theme = "tale-hugo-master"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0