baseURL = 'https://handling1.github.io/unarocaenelmar/'
languageCode = 'en-us'
title = 'Una Roca en el Mar'
theme = "tale-hugo-master"

[Author]
  name = "Se como la roca contra la que rompen sin cesar las olas, manteniéndose firme, a su alrededor se adromecen las turbulencias de la espuma"

[menu]
  [[menu.main]]
    identifier = "informacion"
    name = "Informacion"
    title = "Informacion"
    url = "/informacion/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0

    